# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Herramientas FCI
email: redeploys@ciudadanointeligente.org
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://herramientas.ciudadanointeligente.org" # the base hostname & protocol for your site
twitter_username: fci
github_username:  ciudadanointeligente
analytics: 'UA-76464035-1'

# Build settings
markdown: kramdown

collections:
  tools:
    output: true